# @format

BOT:
  OWNERS: ["901487880067776524", "1355450594185449472"]
  ADMINS: ["901487880067776524", "1313516472462475405", "1243904427631317088"]
  STAFFS: ["901487880067776524"]

LINKS:
  SUPPORT: "https://discord.gg/AZ48HU62vD"
  MONGO_URI: ""

SPOTIFY:
  ID: ""
  SECRET: ""

FUEGO:
  PREFIX: "."
  EMOJIS: "black"
  COLOR: "#00FFFF"
  SHARDS: 2
  PER_CLUSTER: 2
  TOKEN: ""
  TOPGGAUTH: ""
  VOTEURI: "https://top.gg/bot/bot_id/vote"

WEBHOOKS:
  ERROR: ""
  STATIC: ""
  PLAYER: ""
  SERVER: ""
  COMMAND: ""
